[package]
name = "airshipper"
description = "Provides automatic updates for the voxel RPG Veloren."
version = "0.3.2"
authors = ["Songtronix <contact@songtronix.com>"]
edition = "2018"
publish = false
default-run = "airshipper"

license = "GPL-3.0"
homepage = "https://www.veloren.net"
repository = "https://gitlab.com/veloren/airshipper"

[features]
default = ["gui"]
gui = ["iced", "iced_native", "iced_futures"]

# Windows logo
[package.metadata.winres]
OriginalFilename = "Airshipper.exe"
FileDescription = "Launcher for the the multiplayer voxel RPG written in Rust."
LegalCopyright = "Copyright Â© 2020"

[badges]
maintenance = { status = "actively-developed" }

[dependencies]
# Cli
clap = { version = "2.33.0", features = ["yaml"] }
indicatif = "0.14.0"
# UI
iced = { git = "https://github.com/hecrj/iced.git", features = ["debug", "svg", "image"], rev = "99a6f8dbc6f9f50f799906c8104dfff961469fd0", optional = true }
iced_futures = { git = "https://github.com/hecrj/iced.git", features = ["async-std"], rev = "99a6f8dbc6f9f50f799906c8104dfff961469fd0", optional = true }
iced_native = { git = "https://github.com/hecrj/iced.git", rev = "99a6f8dbc6f9f50f799906c8104dfff961469fd0", optional = true }
# logging
log = "0.4.8"
fern = { version = "0.6.0", features = ["colored"] }
chrono = "0.4.11"
# networking
isahc = "0.9.1"
# parsing
html2text = "0.1.11"
strip_markdown = "0.1.0"
rss = "1.9.0"
ron = "0.5.1"
zip = "0.5.5"
serde = "1.0.105"
url = "2.1.1"
semver = "0.9.0"
# other
async-std = { version = "1.5.0", features = ["unstable", "attributes"] }
derive_more = "0.99.3"
lazy_static = "1.4.0"
dirs = "2.0.2"
find_folder = "0.3.0"
# TODO: use futures provides by Iced?
futures = "0.3.4"
opener = "0.4.1"
backtrace = "0.3.45"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3.8", features = ["shellapi", "winuser"] }

[target.'cfg(windows)'.build-dependencies]
winres = "0.1.11"
