hard_tabs = false
version = "Two"

format_code_in_doc_comments = true
format_strings = true
wrap_comments = true

use_try_shorthand = true
reorder_impl_items = false

fn_single_line = false
inline_attribute_width = 0
match_block_trailing_comma = true
imports_granularity = "Crate"
overflow_delimited_expr = true
use_field_init_shorthand = true
max_width = 90
comment_width = 120