#linux, windows, macos builds here as template
.tlinux:
  image: registry.gitlab.com/veloren/veloren-docker-ci/base/linux-x86_64:${CACHE_IMAGE_TAG}
  timeout: 2h
  script:
    - cargo build --release -p airshipper --all-features
    - cargo build --release -p airshipper-server --all-features
    - zip -j $CI_PROJECT_DIR/airshipper-linux target/release/airshipper LICENSE
    - mv target/release/airshipper $CI_PROJECT_DIR
    - mv target/release/airshipper-server $CI_PROJECT_DIR
  artifacts:
    paths:
      - airshipper
      - airshipper-server
      - airshipper-linux.zip
      - LICENSE
    expire_in: 1 week

.twindows:
  image: registry.gitlab.com/veloren/veloren-docker-ci/base/windows-x86_64:${CACHE_IMAGE_TAG}
  timeout: 2h
  script:
    - cargo build --target=x86_64-pc-windows-gnu --release -p airshipper --all-features
    - cargo build --target=x86_64-pc-windows-gnu --release -p airshipper-server --all-features
    - mv target/x86_64-pc-windows-gnu/release/airshipper.exe $CI_PROJECT_DIR
    - mv target/x86_64-pc-windows-gnu/release/airshipper-server.exe $CI_PROJECT_DIR
  artifacts:
    paths:
      - airshipper.exe
      - airshipper-server.exe
      - LICENSE
    expire_in: 1 week

.twindows-installer:
  image: registry.gitlab.com/veloren/veloren-docker-ci/base/windows-x86_64:${CACHE_IMAGE_TAG}
  timeout: 2h
  dependencies:
    - windows-x86_64
  script:
    - chmod +x client/nsis/update_installer_version.sh
    - bash client/nsis/update_installer_version.sh
    - makensis client/nsis/installer.nsi
    - mv client/nsis/airshipper-installer.exe $CI_PROJECT_DIR
  artifacts:
    paths:
      - airshipper-installer.exe
    expire_in: 1 week

# macOS.
# Use a YAML anchor to allow the same before_script to be used in both .build-macos-x86_64 and .build-macos-aarch64.
# https://docs.gitlab.com/ee/ci/yaml/yaml_optimization.html#yaml-anchors-for-scripts
.build-macos-install-script: &build-macos-install-script
  - curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y;
  - wget -q https://github.com/Kitware/CMake/releases/download/v3.31.8/cmake-3.31.8-macos-universal.tar.gz;
  - tar -xzf cmake-3.31.8-macos-universal.tar.gz;
  - ls -la cmake-3.31.8-macos-universal/CMake.app/Contents;
  - sudo cp -r cmake-3.31.8-macos-universal/CMake.app/Contents/bin/* /usr/local/bin/;
  - sudo cp -r cmake-3.31.8-macos-universal/CMake.app/Contents/share/* /usr/local/share/;
  - which cmake;
  - cmake --version;

.build-macos-before-script: &build-macos-before-script
  - source ${HOME}/.cargo/env;
  - cargo --version;
  - rustup toolchain list;
  - export DISABLE_GIT_LFS_CHECK=true;
  - export VELOREN_ASSETS="$(pwd)/assets";
  - echo "VELOREN_ASSETS=${VELOREN_ASSETS}";
  - export RUSTFLAGS="-D warnings";
  - export CARGO_INCREMENTAL=0;

.tmacos:
  tags: ["saas-macos-large-m2pro"]
  image: macos-15-xcode-16
  timeout: 2h
  before_script:
    - *build-macos-install-script
    # Using fat LTO on macos_x86_64 caused timeouts in the build pipeline,
    # overriding it to thin here fixes this.
    - export PROFILE="release-thinlto";
    - *build-macos-before-script
    - rustup target add x86_64-apple-darwin;
    - export RUST_TARGET="x86_64-apple-darwin";
  script:
    - export MACOSX_DEPLOYMENT_TARGET="10.13"
    - cargo build --release -p airshipper --all-features
    - cargo build --release -p airshipper-server --all-features
    - zip -j $CI_PROJECT_DIR/airshipper-macos target/release/airshipper LICENSE
    - mv target/release/airshipper $CI_PROJECT_DIR
    - mv target/release/airshipper-server $CI_PROJECT_DIR
  artifacts:
    paths:
      - airshipper
      - airshipper-server
      - airshipper-macos.zip
      - LICENSE
    expire_in: 1 week

.tmacos-aarch64:
  extends:
    - .tmacos
  before_script:
    - *build-macos-install-script
    - export PROFILE="release";
    - *build-macos-before-script
    - rustup target add aarch64-apple-darwin;
    - export RUST_TARGET="aarch64-apple-darwin";

# Builds for release - all of these export their $CI_JOB_ID to a report artifact that
# is used by the gitlab_release step to include their artifacts in the resulting release
linux-x86_64:
  extends:
    - .tlinux
  stage: build
  # linux-x86_64 doesn't use .treleasetag as airshipper server is deployed on every merge to master
  rules:
    - if: ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_TAG != null)
  after_script:
    - echo LINUX_X86_64_JOB_ID=$CI_JOB_ID >> linux_x86_64_job_id.env
  artifacts:
    reports:
      dotenv: linux_x86_64_job_id.env
  tags: ["veloren/*", "build", "publish", "trusted"]

macos-x86_64:
  extends:
    - .treleasetag
    - .tmacos
  stage: build
  after_script:
    - echo MACOS_X86_64_JOB_ID=$CI_JOB_ID >> macos_x86_64_job_id.env
  artifacts:
    reports:
      dotenv: macos_x86_64_job_id.env

macos-aarch64:
  extends:
    - .treleasetag
    - .tmacos-aarch64
  stage: build
  after_script:
    - echo MACOS_AARCH64_JOB_ID=$CI_JOB_ID >> macos_aarch64_job_id.env
  artifacts:
    reports:
      dotenv: macos_aarch64_job_id.env

windows-x86_64:
  extends:
    - .treleasetag
    - .twindows
  stage: build
  after_script:
    - echo WINDOWS_JOB_ID=$CI_JOB_ID >> windows_job_id.env
  artifacts:
    reports:
      dotenv: windows_job_id.env
  tags: ["veloren/*", "build", "publish", "trusted"]

windows-installer-x86_64:
  extends:
    - .treleasetag
    - .twindows-installer
  stage: build2
  after_script:
    - echo WINDOWS_INSTALLER_JOB_ID=$CI_JOB_ID >> windows_installer_job_id.env
  artifacts:
    reports:
      dotenv: windows_installer_job_id.env
  tags: ["veloren/*", "build", "publish", "trusted"]

# Optional builds - these are in the check stage even though they're builds to allow building
# the output even if code quality checks fail
.tnon-master-optional:
  stage: check
  except:
    - master
  when: manual
  allow_failure: true

opt-linux-x86_64:
  extends:
    - .tlinux
    - .tnon-master-optional
  tags: ["veloren/*", "build"]

opt-macos-x86_64:
  extends:
    - .tmacos
    - .tnon-master-optional

opt-macos-aarch64:
  extends:
    - .tmacos-aarch64
    - .tnon-master-optional

opt-windows-x86_64:
  extends:
    - .twindows
    - .tnon-master-optional
  tags: ["veloren/*", "build"]

opt-windows-installer-x86_64:
  extends:
    - .twindows-installer
    - .tnon-master-optional
  dependencies:
    - opt-windows-x86_64
  stage: build2
  tags: ["veloren/*", "build"]
